- name: Assign Templates to Zabbix Hosts
  hosts: localhost
  collections:
    - community.zabbix
  vars:
    zabbix_api_url: "http://10.0.0.74:8080/api_jsonrpc.php"
    zabbix_user: "Admin"
    zabbix_password: "Admin"
    zabbix_host_name: "{{ inventory_hostname }}"
    zabbix_templates:
      - "Template OS Linux"
  tasks:
    - name: Link templates to host
      zabbix_host:
        server_url: "{{ zabbix_api_url }}"
        login_user: "{{ zabbix_user }}"
        login_password: "{{ zabbix_password }}"
        host_name: "{{ zabbix_host_name }}"
        templates: "{{ zabbix_templates }}"
        state: present
