---
- name: Gather facts from all hosts (Linux and Windows)
  hosts: all
  gather_facts: false
  tasks:
    - name: Gather Linux facts
      ansible.builtin.setup:
      when: ansible_os_family != 'Windows'
      become: yes
    - name: Gather Windows facts
      ansible.windows.setup:
      when: ansible_os_family == 'Windows'
    - name: Display gathered facts summary
      debug:
        msg: "Host {{ inventory_hostname }}: OS = {{ ansible_distribution | default(ansible_os_family) }} {{ ansible_distribution_version | default('') }}, IP = {{ ansible_default_ipv4.address | default('N/A') }}"
