---
- name: Gather facts from all hosts (Linux and Windows)
  hosts: all
  gather_facts: false
  tasks:
    - name: Gather Linux facts
      ansible.builtin.setup:
      when: ansible_os_family != 'Windows'
      become: yes
    - name: Gather Windows facts
      ansible.windows.setup:
      when: ansible_os_family == 'Windows'
